### ISSUE TITLE
Take care of background option

### ISSUE THREAD

**Issue by skywind3000** [phmarek/vim-tosvg#1]
When using dark background themes, svg looks terrible:

![图片](https://user-images.githubusercontent.com/3035071/147704336-acfdfb61-d0f6-42c5-a239-5ffa04664a65.png)

**Comment by phmarek** [comment]
Thanks for the feedback!

I guess this is about the non-existing background, right?
Well, I can see these options:

- Have the embedding HTML define a background color for the SVG element or the container (eg via CSS)
- Put a static background color into the SVG
- Have background colors on the individual text parts

I'd prefer to keep the SVG transparent and use option 1 -- this is the easiest way to get the SVG blend into the containing page.

Option 2 could only use a static dark color, which might conflict with any other content around it; and option 3 means that the rectangles providing background color for the text end up with a ragged right border, which would be even worse.


Or is that issue about the black `|`? These would be returned as syntax ID 0, which I don't know how to handle - `synIDattr` doesn't give me any attributes for ID 0.

**Comment by skywind3000** [comment]
can we have a global option for background transparency?

**Comment by thenewvu** [comment]
I gave an attempt in https://github.com/phmarek/vim-tosvg/pull/3. But the generated svg is not fully displayed in Chrome (I have not tested it in other apps), I think we need a way to calculate the svg viewport.

**Comment by phmarek** [comment]
Thanks... Right now I pushed a different solution -- sorry about that.
